apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: admin
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: <YOUR-GIT-REPO-URL>  # Replace with your Git repository URL
    targetRevision: <YOUR-BRANCH>   # Replace with your branch
    path: kubernetes/helm/charts/admin
    helm:
      releaseName: admin
      values: |
        image:
          repository: <ACCOUNT-ID>.dkr.ecr.<REGION>.amazonaws.com/shopnow/admin
          tag: latest
        
        hpa:
          enabled: true
  
  destination:
    server: https://kubernetes.default.svc
    namespace: shopnow-demo
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
