replicaCount: 1

image:
  repository: mongo
  tag: "6.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 27017
  headless: true

auth:
  enabled: true
  rootUsername: admin
  rootPassword: ShopNowPass123
  database: shopnow

persistence:
  enabled: true
  storageClass: gp3-ssd
  accessMode: ReadWriteOnce
  size: 5Gi
  retentionPolicy:
    whenDeleted: Delete
    whenScaled: Delete

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

readinessProbe:
  enabled: true
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5

livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 20
  timeoutSeconds: 5
