{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-secret
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGODB_URI: {{ .Values.secret.MONGODB_URI | quote }}
  MONGODB_USERNAME: {{ .Values.secret.MONGODB_USERNAME | quote }}
  MONGODB_PASSWORD: {{ .Values.secret.MONGODB_PASSWORD | quote }}
{{- end }}
